### ISSUE TITLE
RtsEnable should be set to true by Default

### ISSUE THREAD

**Issue by shouidar** [OpenLogics/MewtocolNet#11]
**Is your feature request related to a problem? Please describe.**
I have noticed during my tests with FP10SH, FP3SH and FP2 that if RtsEnable is not set to true in TryConnectAsyncSingle, All Serial read operations return an empty buffer (Zero bytes read)

**Describe the solution you'd like**
Add RtsEnable = true,  to the serial port initialisation. 

` serialClient = new SerialPort() {
     PortName = port,
     BaudRate = baud,
     DataBits = dbits,
     RtsEnable = true,              
     Parity = par,
     StopBits = sbits,
     ReadTimeout = 100,
     Handshake = Handshake.None
 };`

**Comment by Sandoun** [comment]
Thats likely an oversight by me, i did only have access to the FP-XH / FP-X series plcs during testing. Looking into this!
