### ISSUE TITLE
GetMetadataAsync fails with  FP10SH, FP02-C and FP3SH

### ISSUE THREAD

**Issue by shouidar** [OpenLogics/MewtocolNet#13]
**Describe the bug**
While connecting to FP10SH, FP3SH or FP2 the ProgramCapacity returned by the RT command is always zero. Thus the GetMetadataAsync will always throw an exception causing the programm to crash.

**To Reproduce**
Use the BasicRegisterReadWrite Example to connect to on of the plcs above using the serial port.

**Expected behavior**
Expect connection to work with these models

**Screenshots**
![programcapacity0](https://github.com/OpenLogics/MewtocolNet/assets/10144958/216923f5-2d35-478b-ac95-8d37110e4bf6)

**Comment by shouidar** [comment]
Workarround is to set AlwaysGetMetaData to false during initialization:

`.WithInterfaceSettings( ifs => {
            ifs.AlwaysGetMetadata = false;

        })`

**Comment by Sandoun** [comment]
This is a fpwinpro feature and just uses the normal DT area, so maybe this function should be disabled by default.. Thx for the input!
