### ISSUE TITLE
An instruction, but I don't know how to send it

### ISSUE THREAD

**Issue by ms1094392787** [OpenLogics/MewtocolNet#18]
I now have this directive,
```
%01#RCSR0300**\r
```
which returns a bool. But I don't know how to send this command using this library (I've been looking through the source code hard and tried it many times).

**Comment by Sandoun** [comment]
Hello, there is no need to send the individual command directly. Use the pre made layer to read boolean registers. Have a look at the examples: https://github.com/OpenLogics/MewtocolNet/blob/master/Examples%2FExamples.BasicRegisterReadWrite%2FProgram.cs#L58
